<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>prova</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                font-family: 'Lato', sans-serif;
                color: black;
                font-size: 40px;
                margin-top: 5px;
            }

            h1 {
                color: black;
                letter-spacing: -3px;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                font-size: 60px;
                font-weight: 100;
                margin-bottom: 0;
                text-align: center;
            }
            .criar {
                font-family: 'Lato', sans-serif;
                font-size: 25px;
            }
            .texto{
                font-size: 25px;
            }


        </style>
    </head>

    <h1>Mvoigt camionetes</h1> 
    <body>
        <div>    
            <div class="modelo">Modelo:
            <input class="texto" type="text"></div>
            <div class="marca">Marca:
            <input class="texto" type="text"></div>
            <div class="ano">Ano:
            <input class="texto" type="text"></div>
            <button class="criar">Buscar</button>
        </div>

            

    </body>
</html>
